In [5]:
import numpy as np
import pandas as pd
print(pd.__version__)
df = pd.read_csv("https://raw.githubusercontent.com/GabrielOliv235/imersao_dados/refs/heads/main/pandas_imersao/salaries.csv")
df.head(10)

3.0.0

,work_year,experience_level,employment_type,job_title,salary,salary_currency,salary_in_usd,employee_residence,remote_ratio,company_location,company_size
0,2025.0,SE,FT,Solutions Engineer,214000,USD,214000,US,100,US,M
1,2025.0,SE,FT,Solutions Engineer,136000,USD,136000,US,100,US,M
2,2025.0,MI,FT,Data Engineer,158800,USD,158800,AU,0,AU,M
3,2025.0,MI,FT,Data Engineer,139200,USD,139200,AU,0,AU,M
4,2025.0,EN,FT,Data Engineer,90000,USD,90000,US,0,US,M
5,2025.0,EN,FT,Data Engineer,80000,USD,80000,US,0,US,M
6,2025.0,SE,FT,Data Scientist,185000,USD,185000,US,0,US,M
7,2025.0,SE,FT,Data Scientist,148000,USD,148000,US,0,US,M
8,2025.0,MI,FT,Data Scientist,135000,USD,135000,CA,0,CA,M
9,2025.0,MI,FT,Data Scientist,108000,USD,108000,CA,0,CA,M

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 133349 entries, 0 to 133348
Data columns (total 11 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   work_year           133339 non-null  float64
 1   experience_level    133349 non-null  str
 2   employment_type     133349 non-null  str
 3   job_title           133349 non-null  str
 4   salary              133349 non-null  int64
 5   salary_currency     133349 non-null  str
 6   salary_in_usd       133349 non-null  int64
 7   employee_residence  133349 non-null  str
 8   remote_ratio        133349 non-null  int64
 9   company_location    133349 non-null  str
 10  company_size        133349 non-null  str
dtypes: float64(1), int64(3), str(7)
memory usage: 11.2 MB

In [7]:
df.describe()

           work_year        salary  salary_in_usd   remote_ratio
count  133339.000000  1.333490e+05  133349.000000  133349.000000
mean     2024.358770  1.632833e+05  157617.272098      20.905669
std         0.680627  2.173860e+05   74288.363097      40.590044
min      2020.000000  1.400000e+04   15000.000000       0.000000
25%      2024.000000  1.060200e+05  106000.000000       0.000000
50%      2024.000000  1.470000e+05  146206.000000       0.000000
75%      2025.000000  1.990000e+05  198000.000000       0.000000
max      2025.000000  3.040000e+07  800000.000000     100.000000

In [8]:
df.shape

(133349, 11)

In [9]:
linhas, colunas = df.shape
print(f'╔{"═"*25}╗\n║ DIMENSÕES DO DATASET    ║\n╠{"═"*25}╣\n║ • Linhas: {linhas:<13} ║\n║ • Colunas: {colunas:<13}║\n╚{"═"*25}╝')

╔═════════════════════════╗
║ DIMENSÕES DO DATASET    ║
╠═════════════════════════╣
║ • Linhas: 133349        ║
║ • Colunas: 11           ║
╚═════════════════════════╝

In [10]:
df.columns

Index(['work_year', 'experience_level', 'employment_type', 'job_title',
       'salary', 'salary_currency', 'salary_in_usd', 'employee_residence',
       'remote_ratio', 'company_location', 'company_size'],
      dtype='str')

In [11]:
novos_nomes = {
    'work_year': 'ano',
    'experience_level': 'senioridade',
    'employment_type': 'contrato',
    'job_title': 'cargo',
    'salary': 'salario',
    'salary_currency': 'moeda',
    'salary_in_usd': 'usd',
    'employee_residence': 'residencia',
    'remote_ratio': 'remoto',
    'company_location': 'empresa',
    'company_size': 'tamanho_empresa'
}
df.rename(columns=novos_nomes, inplace=True)

In [59]:
df.head()

,ano,senioridade,contrato,cargo,salario,moeda,usd,residencia,remoto,empresa,tamanho_empresa
0,2025.0,SE,FT,Solutions Engineer,214000,USD,214000,US,100,US,M
1,2025.0,SE,FT,Solutions Engineer,136000,USD,136000,US,100,US,M
2,2025.0,MI,FT,Data Engineer,158800,USD,158800,AU,0,AU,M
3,2025.0,MI,FT,Data Engineer,139200,USD,139200,AU,0,AU,M
4,2025.0,EN,FT,Data Engineer,90000,USD,90000,US,0,US,M

In [12]:
df['senioridade'].value_counts()

senioridade
SE    77241
MI    40465
EN    12443
EX     3200
Name: count, dtype: int64

In [13]:
df['contrato'].value_counts()

contrato
FT    132563
CT       394
PT       376
FL        16
Name: count, dtype: int64

In [14]:
df['remoto'].value_counts()

remoto
0      105312
100     27718
50        319
Name: count, dtype: int64

In [15]:
df['tamanho_empresa'].value_counts()

tamanho_empresa
M    129561
L      3574
S       214
Name: count, dtype: int64

In [64]:
senioridade = {
    'SE': 'senior',
    'MI': 'pleno',
    'EN': 'junior',
    'EX': 'executivo'
}
df['senioridade'] = df['senioridade'].replace(senioridade)

In [65]:
df['senioridade'].value_counts()

senioridade
senior       77241
pleno        40465
junior       12443
executivo     3200
Name: count, dtype: int64

In [66]:
contrato = {
    'FT': 'integral',
    'PT': 'parcial',
    'CT': 'contrato',
    'FL': 'freelancer'
}
df['contrato'] = df['contrato'].replace(contrato)

In [67]:
df['contrato'].value_counts()

contrato
integral      132563
contrato         394
parcial          376
freelancer        16
Name: count, dtype: int64

In [68]:
tamanho_empresa = {
    'L': 'grande',
    'S': 'pequena',
    'M':	'media'
}
df['tamanho_empresa'] = df['tamanho_empresa'].replace(tamanho_empresa)

In [69]:
df['tamanho_empresa'].value_counts()

tamanho_empresa
media      129561
grande       3574
pequena       214
Name: count, dtype: int64

In [70]:
mapa_trabalho = {
    0: 'presencial',
    100: 'remoto',
    50: 'hibrido'
}
df['remoto'] = df['remoto'].replace(mapa_trabalho)

In [71]:
df['remoto'].value_counts()

remoto
presencial    105312
remoto         27718
hibrido          319
Name: count, dtype: int64

In [74]:
df.head(30)

,ano,senioridade,contrato,cargo,salario,moeda,usd,residencia,remoto,empresa,tamanho_empresa
0,2025.0,senior,integral,Solutions Engineer,214000,USD,214000,US,remoto,US,media
1,2025.0,senior,integral,Solutions Engineer,136000,USD,136000,US,remoto,US,media
2,2025.0,pleno,integral,Data Engineer,158800,USD,158800,AU,presencial,AU,media
3,2025.0,pleno,integral,Data Engineer,139200,USD,139200,AU,presencial,AU,media
4,2025.0,junior,integral,Data Engineer,90000,USD,90000,US,presencial,US,media
5,2025.0,junior,integral,Data Engineer,80000,USD,80000,US,presencial,US,media
6,2025.0,senior,integral,Data Scientist,185000,USD,185000,US,presencial,US,media
7,2025.0,senior,integral,Data Scientist,148000,USD,148000,US,presencial,US,media
8,2025.0,pleno,integral,Data Scientist,135000,USD,135000,CA,presencial,CA,media
9,2025.0,pleno,integral,Data Scientist,108000,USD,108000,CA,presencial,CA,media
10,2025.0,pleno,integral,BI Developer,118000,USD,118000,US,remoto,US,media
11,2025.0,pleno,integral,BI Developer,51000,USD,51000,US,remoto,US,media
12,2025.0,junior,integral,Data Analyst,91900,USD,91900,US,presencial,US,media
13,2025.0,junior,integral,Data Analyst,54300,USD,54300,US,presencial,US,media
14,2025.0,senior,integral,Applied Scientist,255000,USD,255000,US,presencial,US,media
15,2025.0,senior,integral,Applied Scientist,190000,USD,190000,US,presencial,US,media
16,2025.0,pleno,integral,Systems Engineer,196350,USD,196350,US,presencial,US,media
17,2025.0,pleno,integral,Systems Engineer,130900,USD,130900,US,presencial,US,media
18,2025.0,executivo,integral,Director,170000,USD,170000,US,presencial,US,media
19,2025.0,executivo,integral,Director,160000,USD,160000,US,presencial,US,media
20,2025.0,pleno,integral,Associate,119000,USD,119000,CA,presencial,CA,media
21,2025.0,pleno,integral,Associate,105000,USD,105000,CA,presencial,CA,media
22,2025.0,pleno,integral,Associate,120000,USD,120000,US,presencial,US,media
23,2025.0,pleno,integral,Associate,110000,USD,110000,US,presencial,US,media
24,2025.0,pleno,integral,Associate,120000,USD,120000,US,presencial,US,media
25,2025.0,pleno,integral,Associate,110000,USD,110000,US,presencial,US,media
26,2025.0,pleno,integral,Associate,120000,USD,120000,US,presencial,US,media
27,2025.0,pleno,integral,Associate,110000,USD,110000,US,presencial,US,media
28,2025.0,senior,integral,Software Engineer,190000,USD,190000,US,presencial,US,media
29,2025.0,senior,integral,Software Engineer,150000,USD,150000,US,presencial,US,media

In [78]:
df.describe(include=["object", "string"])

,senioridade,contrato,cargo,moeda,residencia,remoto,empresa,tamanho_empresa
count,133349,133349,133349,133349,133349,133349,133349,133349
unique,4,4,390,26,102,3,95,3
top,senior,integral,Data Scientist,USD,US,presencial,US,media
freq,77241,132563,17314,126140,119579,105312,119641,129561

In [17]:
df.isnull().sum()

ano                10
senioridade         0
contrato            0
cargo               0
salario             0
moeda               0
usd                 0
residencia          0
remoto              0
empresa             0
tamanho_empresa     0
dtype: int64

In [18]:
df['ano'].unique()

array([2025.,   nan, 2024., 2022., 2023., 2020., 2021.])

In [23]:
df[df.isnull().any(axis=1)]

,ano,senioridade,contrato,cargo,salario,moeda,usd,residencia,remoto,empresa,tamanho_empresa
5588,NaN,SE,FT,Product Manager,184500,USD,184500,US,0,US,M
59692,NaN,MI,FT,Engineer,110000,USD,110000,DE,0,DE,M
59710,NaN,EN,FT,Data Scientist,208800,USD,208800,US,0,US,M
59759,NaN,SE,FT,Software Engineer,135000,USD,135000,US,0,US,M
59789,NaN,SE,FT,Engineer,112000,USD,112000,US,0,US,M
131000,NaN,SE,FT,Machine Learning Engineer,163800,USD,163800,US,0,US,M
131006,NaN,SE,FT,Data Analytics Manager,204500,USD,204500,US,0,US,M
133054,NaN,EN,FT,Data Scientist,40000,USD,40000,JP,100,MY,L
133281,NaN,MI,FT,Machine Learning Engineer,180000,PLN,46597,PL,100,PL,L
133317,NaN,MI,FT,Data Scientist,130000,USD,130000,US,50,US,L

In [ ]:
import numpy as np

df_salarios = pd.DataFrame({
    'nome': ['Ana', 'Bruno', 'Carlos', 'Diana', 'Eduardo'],
    'salario': [4000, np.nan, 3500, np.nan, 5000]
})
df_salarios['salario_media'] = df_salarios['salario'].fillna(df_salarios['salario'].mean().round(2))
df_salarios['salario_mediana'] = df_salarios['salario'].fillna(df_salarios['salario'].median())
df_salarios